"""Tests for Human Field x Base-12 Pullback Atlas v0.1.

Synthetic / minimal fixtures only. NO real frozen pullback data is loaded and
NO canonical atlas output is generated by this test module.
"""

import datetime
from datetime import date

import numpy as np
import pytest

import candidate_c_lens
import human_field_base12_pullback_atlas as atlas
from candidate_b_loader import ReducedTrades, _load_one_csv


# ── fixtures ──────────────────────────────────────────────────────────────────

def _spy_frame(n_sessions: int, start=date(2000, 1, 3), rvol_trend=False):
    """Ascending synthetic SPY frame. Calendar-day spacing is fine: the atlas
    indexes by *session position*, not calendar gaps."""
    dates = [start + datetime.timedelta(days=i) for i in range(n_sessions)]
    adj = np.array([100.0 * (1.0 + 0.0001 * i) for i in range(n_sessions)])
    if rvol_trend:
        # oscillation amplitude grows with i -> rolling std strictly
        # increasing in time (a linear ramp would have constant std).
        lr = np.array(
            [1e-4 * i * (1 if i % 2 == 0 else -1) for i in range(n_sessions)]
        )
    else:
        lr = np.array([0.001 if i % 2 == 0 else -0.001 for i in range(n_sessions)])
    return atlas.SpyFrame(dates=dates, adj_close=adj, log_return=lr)


def _reduced(entry_dates, directions, r_multiples, assets):
    n = len(entry_dates)
    is_long = np.array([d == "long" for d in directions], dtype=bool)
    return ReducedTrades(
        trade_id=np.arange(n, dtype=np.int64),
        asset=np.asarray(assets, dtype=object),
        entry_date=np.asarray(entry_dates, dtype=object),
        exit_date=np.asarray(entry_dates, dtype=object),
        is_long=is_long,
        r_multiple=np.asarray(r_multiples, dtype=np.float64),
        frozen_artifact_id=np.asarray(["synthetic"] * n, dtype=object),
    )


# ── 1. single-anchor phase function, not the 365-DOY surface ──────────────────

def test_uses_single_anchor_phase_function():
    # Binding check (robust): the single-anchor function is bound; the
    # 365-DOY surface function is NOT imported into the atlas namespace.
    assert atlas.assign_annual_sector_phase is (
        candidate_c_lens.assign_annual_sector_phase
    )
    assert not hasattr(atlas, "assign_anchor_shifted_phase")
    assert not hasattr(atlas, "enumerate_anchor_doys")


def test_phases_match_candidate_c_single_anchor(monkeypatch):
    def _boom(*a, **k):  # surface function must never be called
        raise AssertionError("assign_anchor_shifted_phase was called")

    monkeypatch.setattr(candidate_c_lens, "assign_anchor_shifted_phase", _boom)
    spy = _spy_frame(400)
    trades = _reduced([date(2001, 6, 1)], ["long"], [1.0], ["SPY"])
    ev = atlas.build_events(trades, spy)[0]
    assert ev.base12_phase == candidate_c_lens.assign_annual_sector_phase(
        date(2001, 6, 1), 12
    )
    assert ev.base10_phase == candidate_c_lens.assign_annual_sector_phase(
        date(2001, 6, 1), 10
    )
    assert 0 <= ev.base12_phase <= 11 and 0 <= ev.base10_phase <= 9


# ── 2. substrate validation ───────────────────────────────────────────────────

def test_validate_substrate_rejects_wrong_row_count():
    trades = _reduced([date(2010, 1, 1)], ["long"], [1.0], ["SPY"])
    with pytest.raises(atlas.ImplementationCheckFailed):
        atlas.validate_substrate(trades)


def test_validate_substrate_rejects_post_bound_entry_date():
    eds = [date(2010, 1, 1)] * atlas.EXPECTED_POOLED_ROW_COUNT
    eds[0] = date(2023, 1, 5)  # past the permitted entry-date bound
    assets = (
        ["SPY"] * 243 + ["EFA"] * 283 + ["EEM"] * 261
        + ["GLD"] * 253 + ["TLT"] * 242
    )
    trades = _reduced(eds, ["long"] * len(eds), [1.0] * len(eds), assets)
    with pytest.raises(atlas.ImplementationCheckFailed):
        atlas.validate_substrate(trades)


# ── 3. direction-domain assertion (reused audited loader; throws) ─────────────

def test_direction_domain_throws_on_unexpected(tmp_path):
    csv = tmp_path / "bad.csv"
    csv.write_text(
        "entry_date,exit_date,direction,r_multiple\n"
        "2010-01-05,2010-01-09,sideways,1.0\n"
    )
    with pytest.raises(ValueError):
        _load_one_csv(str(tmp_path), "bad.csv", "SPY")


# ── 4. t-1 windowing: the event day is never read ─────────────────────────────

def test_feature_window_ends_strictly_before_entry_date():
    spy = _spy_frame(400)
    entry = spy.dates[300]
    pos = spy.session_index_strictly_before(entry)
    assert spy.dates[pos] < entry
    assert pos == 299
    # a date equal to a session returns the prior session, not that session
    assert spy.session_index_strictly_before(spy.dates[0]) is None


# ── 5. realized-vol percentile estimator (Q2 empirical CDF) ───────────────────

def test_empirical_cdf_strictly_less():
    trailing = [1.0, 2.0, 3.0, 3.0, 4.0]
    assert atlas.empirical_cdf_pctile(trailing, 3.0) == pytest.approx(2 / 5)
    assert atlas.empirical_cdf_pctile(trailing, 5.0) == pytest.approx(5 / 5)
    assert atlas.empirical_cdf_pctile(trailing, 0.5) == pytest.approx(0.0)


# ── 6. high/low arousal threshold (>= 0.75) ───────────────────────────────────

def test_arousal_threshold_boundary():
    assert atlas.is_high_arousal(0.75) is True
    assert atlas.is_high_arousal(0.7499999) is False
    assert atlas.is_high_arousal(1.0) is True


# ── 7. indeterminate-state when lookback history is insufficient ──────────────

def test_indeterminate_on_insufficient_history():
    spy = _spy_frame(10)  # far fewer than 252 trailing sessions
    sf = atlas.compute_state_features(spy, spy.dates[-1] + datetime.timedelta(days=1))
    assert sf.state == atlas.STATE_INDETERMINATE
    assert sf.indeterminate_reason is not None


def test_state_resolves_with_enough_history():
    spy = _spy_frame(400, rvol_trend=True)
    entry = spy.dates[-1] + datetime.timedelta(days=1)
    sf = atlas.compute_state_features(spy, entry)
    assert sf.state in (
        atlas.STATE_CALM_BULL,
        atlas.STATE_MANIC,
        atlas.STATE_PANIC,
        atlas.STATE_QUIET_BEAR,
    )
    # rvol strictly increasing in time -> current is the max -> high arousal;
    # adj_close strictly increasing -> 30d return > 0 -> positive valence.
    assert sf.state == atlas.STATE_MANIC


# ── 8. low-data flag n < 20 ───────────────────────────────────────────────────

def test_low_data_flag_threshold():
    spy = _spy_frame(400, rvol_trend=True)
    eds = [date(2001, 6, 1)] * 5  # only 5 events -> every populated cell low-data
    trades = _reduced(eds, ["long"] * 5, [1.0] * 5, ["SPY"] * 5)
    events = atlas.build_events(trades, spy)
    cells = atlas.grid1_event_count(events)
    populated = [c for c in cells if c.n > 0]
    assert populated and all(c.low_data and c.marker == "LOW_DATA" for c in populated)
    # full cartesian still emitted (incl. empty cells)
    assert len(cells) == atlas.BASE12 * len(atlas.STATE_ORDER)


# ── 9. degenerate PSS -> NA, never silently 0.0 ───────────────────────────────

def test_degenerate_pss_returns_na():
    spy = _spy_frame(400, rvol_trend=True)
    eds = [date(2001, 6, 1), date(2001, 9, 1)]
    trades = _reduced(eds, ["long", "long"], [1.0, 2.0], ["SPY", "SPY"])
    events = atlas.build_events(trades, spy)
    rows = atlas.grid4_state_pss(events)
    populated = [r for r in rows if r["n"] > 0]
    assert populated
    for r in populated:  # all-long -> total variance 0 -> NA, not 0.0
        assert r["pss_12"] is atlas.NA
        assert r["pss_10"] is atlas.NA


def test_pss_defined_when_mixed_direction():
    spy = _spy_frame(400, rvol_trend=True)
    eds = [date(2001, 4, 1), date(2001, 10, 1)]
    trades = _reduced(eds, ["long", "short"], [1.0, -1.0], ["SPY", "SPY"])
    events = atlas.build_events(trades, spy)
    rows = atlas.grid4_state_pss(events)
    vals = [r["pss_12"] for r in rows if r["n"] > 0]
    assert vals and all(isinstance(v, float) for v in vals)


# ── 10. median convention (even n -> average of two middle) ───────────────────

def test_median_convention():
    assert atlas._median([1.0, 2.0, 3.0, 4.0]) == pytest.approx(2.5)
    assert atlas._median([3.0, 1.0, 2.0]) == pytest.approx(2.0)
    assert atlas._median([]) is atlas.NA


# ── 11. grid completeness / no curated subset ─────────────────────────────────

def test_grids_emit_full_cartesian():
    spy = _spy_frame(400, rvol_trend=True)
    eds = [date(2001, 6, 1)] * 3
    trades = _reduced(eds, ["long"] * 3, [1.0] * 3, ["SPY"] * 3)
    events = atlas.build_events(trades, spy)
    assert len(atlas.grid1_event_count(events)) == 12 * 5
    assert len(atlas.grid2_long_pct(events)) == 12 * 5
    assert len(atlas.grid3_median_r(events)) == 12 * 5
    assert len(atlas.grid5_asset_phase_state(events)) == 5 * 12 * 5
    assert len(atlas.grid8_base10_views(events)["count"]) == 10 * 5
    assert len(atlas.grid4_state_pss(events)) == len(atlas.STATE_ORDER)


def test_sparsity_report_counts_low_data():
    spy = _spy_frame(400, rvol_trend=True)
    eds = [date(2001, 6, 1)] * 3
    trades = _reduced(eds, ["long"] * 3, [1.0] * 3, ["SPY"] * 3)
    events = atlas.build_events(trades, spy)
    g1 = atlas.grid1_event_count(events)
    rep = atlas.grid7_sparsity_report({"grid1": g1})[0]
    assert rep["total_cells"] == 60
    assert rep["low_data_cells"] == 60  # 3 events: every cell is < 20


# ── 12. bounded SPY frame: no post-2022 row survives truncation ───────────────

def test_build_spy_frame_filters_post_2022():
    dates = [date(2022, 12, 19), date(2022, 12, 20), date(2022, 12, 21),
             date(2023, 1, 3), date(2024, 6, 1)]
    spy = atlas.build_spy_frame(
        dates, [100.0, 101.0, 102.0, 103.0, 104.0], [0.0, 0.01, 0.0, 0.02, 0.0]
    )
    assert max(spy.dates) <= atlas.MAX_PERMITTED_FEATURE_DATE
    assert date(2023, 1, 3) not in spy.dates
    assert date(2024, 6, 1) not in spy.dates
    assert len(spy) == 2  # only 2022-12-19 and 2022-12-20


def test_metadata_declares_no_post_2022_and_exploratory():
    md = atlas.build_metadata(
        "20260517_000000", {"x": "y"}, atlas.EXPECTED_POOLED_ROW_COUNT,
        atlas.EXPECTED_ASSET_COUNTS, "ok", 0,
    )
    assert md["post_2022_rows_used_in_computation"] is False
    assert md["exploratory_atlas_only"] is True
    assert md["verdict_language_allowed"] is False
    assert md["confirmation_claim_allowed"] is False
    assert md["lane2_attention_spike_study_included"] is False
    assert md["no_oos_analysis"] is True


# ── preflight QA: indeterminate count > 0 blocks the summary ──────────────────

def test_preflight_flags_indeterminate(monkeypatch):
    spy = _spy_frame(400, rvol_trend=True)
    eds = [date(2001, 6, 1)] * atlas.EXPECTED_POOLED_ROW_COUNT
    assets = (
        ["SPY"] * 243 + ["EFA"] * 283 + ["EEM"] * 261
        + ["GLD"] * 253 + ["TLT"] * 242
    )
    trades = _reduced(eds, ["long"] * len(eds), [1.0] * len(eds), assets)
    events = atlas.build_events(trades, spy)
    # force one indeterminate event
    events[0] = atlas.AtlasEvent(
        **{**events[0].__dict__, "state": atlas.STATE_INDETERMINATE,
           "indeterminate_reason": "synthetic"}
    )
    status, details = atlas.preflight(trades, spy, events)
    assert status == "implementation_check_failed"
    assert details["indeterminate_count"] == 1
    assert "qa_warning" in details


def test_canonical_runner_refuses_without_authorization():
    import importlib.util
    import os

    path = os.path.join(
        os.path.dirname(__file__), "..", "scripts",
        "run_human_field_base12_pullback_atlas.py",
    )
    spec = importlib.util.spec_from_file_location("hf_runner", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    assert mod.CANONICAL_RUN_AUTHORIZED is False
    with pytest.raises(SystemExit):
        mod.run_canonical(os.getcwd())
