"""Missing-source retry/backoff + stable-404 + operator-authorized allowlist
amendment tests (no-network, value-blind) for the TTG archive build path.

Covers the amendment contract:
  1. Pre-amendment synthetic GOLDEN reproduction (non-circular): the golden was
     captured from clean 91c9f2b (fetch module SHA 1d069087…) BEFORE any edit;
     the amended code reproduces the exact archive + provenance-structural hashes
     under empty-allowlist all-success conditions. The test also proves the module
     CHANGED since capture, so the baseline was not generated by amended code.
  2. Transient fetch failure then success: bounded retry/backoff recovers; output
     equals the all-success baseline; streaming high-water stays 2*EDD+1 = 3.
  3. Retry exhaustion: transient beyond the bounded budget hard-fails cleanly.
  4. Stable 404 on an ALLOWLISTED date: deliberate tolerated fetch-absent gap;
     build continues.
  5. Stable 404 on a NON-allowlisted date: terminal hard-fail.
  6. Coverage propagation (two-sided): missing source 2022-11-10 (allowlisted)
     excludes SQLDATEs 2022-11-09/10/11 and retains 2022-11-08/12.
  7. Existing 2014 mutual-absence gap regression (unification did not perturb it).
  8. Empty-allowlist all-success equivalence (explicit empty allowlist param).
  9. Unknown stable 404 remains hard-fail (default empty/strict allowlist).
 plus: exception classifier unit checks; committed default allowlist is empty.

All tests run under an autouse no-network backstop with the source gate False, a
fake sleep_fn (no real-time sleep), and small bounded retry counts.
"""

from __future__ import annotations

import datetime
import hashlib
import http.client
import inspect
import json
import urllib.error

import pytest

import lane2_type_tone_goldstein_archive_fetch_path as fp
import lane2_type_tone_goldstein_local_archive as archive


# ── pre-amendment GOLDEN, captured from clean 91c9f2b BEFORE any edit ─────────
# Capture harness: /tmp/ttg_golden_capture.py (recorded in the amendment report).
GOLDEN_CAPTURED_FROM_HEAD = "91c9f2bd23241370939d3ce199643a66b1827568"
GOLDEN_CAPTURED_FROM_FETCH_SHA = (
    "1d069087f65fc604f976aea81fe3f2f7f3f65e44e6de2cbc94bc2afbb8f807e4"
)
GOLDEN_ARCHIVE_SHA256 = (
    "e9f66699a179a17eb2d591224395bf2c3f9962715e696cea933d8151766aeac8"
)
GOLDEN_ARCHIVE_BYTE_SIZE = 605
GOLDEN_ARCHIVE_ROW_COUNT = 24
GOLDEN_PROVENANCE_DIGEST = (
    "ba1bb1264c6b538271afcc8024947562f1f350de3135a703a5fd73e6e7e66c5d"
)


# ── suite-wide no-network backstop ───────────────────────────────────────────

@pytest.fixture(autouse=True)
def _no_network(monkeypatch):
    assert fp.REAL_FETCH_SOURCE_GATE_ENABLED is False

    def _boom(*_a, **_k):
        raise AssertionError("no-network backstop: _open_url must not be called")

    monkeypatch.setattr(fp, "_open_url", _boom)
    yield


# ── helpers (synthetic, value-blind) ─────────────────────────────────────────

_N = 58


def _row(sqldate_iso):
    cells = ["FILLER"] * _N
    cells[archive.DATE_FIELD_COLUMN_INDEX] = sqldate_iso.replace("-", "")
    cells[archive.QUADCLASS_COLUMN_INDEX] = "4"
    cells[archive.GOLDSTEINSCALE_COLUMN_INDEX] = "1.0"
    cells[archive.NUMMENTIONS_COLUMN_INDEX] = "5"
    cells[archive.AVGTONE_COLUMN_INDEX] = "0.5"
    return "\t".join(cells)


def _payload(rows):
    return ("\n".join(rows) + "\n").encode("utf-8")


def _d(y, m, day):
    return datetime.date(y, m, day)


def _iso(dt):
    return dt.isoformat()


def _mk_manifests(file_map):
    md5 = ["{}  {}".format(hashlib.md5(b).hexdigest(), fn) for fn, b in file_map.items()]
    siz = ["{} {}".format(len(b), fn) for fn, b in file_map.items()]
    return (("\n".join(md5) + "\n").encode(), ("\n".join(siz) + "\n").encode())


def _guarded(monkeypatch):
    monkeypatch.setattr(
        archive, "TYPE_TONE_GOLDSTEIN_LOCAL_ARCHIVE_BUILD_AUTHORIZED", True)
    return dict(cli_flag=True, module_authorized=True, env={archive.ENV_GUARD_NAME: "1"})


class _FakeSleep:
    """Records backoff durations; never sleeps in real time."""

    def __init__(self):
        self.calls = []

    def __call__(self, seconds):
        self.calls.append(seconds)


def _http_404(url="http://data.gdeltproject.org/x"):
    return urllib.error.HTTPError(url, 404, "Not Found", None, None)


def _http_503(url="http://data.gdeltproject.org/x"):
    return urllib.error.HTTPError(url, 503, "Service Unavailable", None, None)


# ── §1 GOLDEN synthetic window (mirrors /tmp/ttg_golden_capture.py exactly) ───

def _golden_window():
    base = _d(2014, 6, 1)
    present = [base + datetime.timedelta(days=i) for i in range(10)]
    payloads = {}
    for f in present:
        rows = [_row(_iso(f - datetime.timedelta(days=1))),
                _row(_iso(f)),
                _row(_iso(f + datetime.timedelta(days=1)))]
        payloads[f] = _payload(rows)
    file_map = {fp.expected_source_filename(d): payloads[d] for d in present}
    md5_b, size_b = _mk_manifests(file_map)
    return ("2014-06-01", "2014-06-10", present, payloads, md5_b, size_b)


def _golden_digest(res):
    canon = {
        "archive_sha256": res["archive_artifact"]["sha256"],
        "archive_byte_size": res["archive_artifact"]["byte_size"],
        "archive_row_count": res["archive_artifact"]["row_count"],
        "primary_covered_sqldates": res["primary_covered_sqldates"],
        "ledger_covered_sqldates": res["ledger_covered_sqldates"],
        "ledger_edge_excluded_sqldates": res["ledger_edge_excluded_sqldates"],
        "ledger_gap_uncovered_sqldates": res["ledger_gap_uncovered_sqldates"],
        "tolerated_gap_dates": res["tolerated_gap_dates"],
        "fetched_dates": res["fetched_dates"],
        "agg_raw_rows": res["agg_raw_rows"],
        "agg_date_eligibility_failure": res["agg_date_eligibility_failure"],
        "agg_edge_window_exclusion": res["agg_edge_window_exclusion"],
        "agg_classify_retained": res["agg_classify_retained"],
        "primary_archive_rows": res["primary_archive_rows"],
        "max_buffered_source_file_blocks": res["max_buffered_source_file_blocks"],
        "streaming_release_depth": res["streaming_release_depth"],
        "reconcile_status": res["reconcile_status"],
        "coverage_summary": res["manifest"]["coverage_summary"],
    }
    blob = json.dumps(canon, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(blob).hexdigest()


class _Fetcher:
    def __init__(self, payloads):
        self.payloads = payloads
        self.dates = []

    def __call__(self, source_file_date, url):
        self.dates.append(source_file_date)
        return self.payloads[source_file_date]


def _run_golden(monkeypatch, tmp_path, *, fetch_absent_allowlist=None, out="g"):
    start, end, present, payloads, md5_b, size_b = _golden_window()
    res = fp.run_bounded_integrity_build(
        start, end, out_dir=str(tmp_path / out),
        md5sums_bytes=md5_b, filesizes_bytes=size_b,
        fetch_callable=_Fetcher(payloads),
        fetch_absent_allowlist=fetch_absent_allowlist,
        sleep_fn=_FakeSleep(), **_guarded(monkeypatch))
    return res


def test_non_circular_baseline_module_changed_since_capture():
    """Prove the golden was NOT generated by amended code: the live fetch module
    SHA differs from the SHA the golden was captured under (1d069087…)."""
    with open(fp.__file__, "rb") as fh:
        live_sha = hashlib.sha256(fh.read()).hexdigest()
    assert live_sha != GOLDEN_CAPTURED_FROM_FETCH_SHA, (
        "golden must come from pre-amendment code; module is unchanged?")


def test_amended_reproduces_preamendment_golden(monkeypatch, tmp_path):
    res = _run_golden(monkeypatch, tmp_path)
    assert res["archive_artifact"]["sha256"] == GOLDEN_ARCHIVE_SHA256
    assert res["archive_artifact"]["byte_size"] == GOLDEN_ARCHIVE_BYTE_SIZE
    assert res["archive_artifact"]["row_count"] == GOLDEN_ARCHIVE_ROW_COUNT
    assert _golden_digest(res) == GOLDEN_PROVENANCE_DIGEST


# ── §8 empty-allowlist all-success equivalence (explicit empty param) ─────────

def test_empty_allowlist_all_success_equivalence(monkeypatch, tmp_path):
    res = _run_golden(monkeypatch, tmp_path, fetch_absent_allowlist=[])
    assert res["archive_artifact"]["sha256"] == GOLDEN_ARCHIVE_SHA256
    assert _golden_digest(res) == GOLDEN_PROVENANCE_DIGEST
    assert res["fetch_absent_allowlist_supplied"] == []
    assert res["fetch_absent_allowlisted_source_dates"] == []


# ── committed default allowlist is empty / strict ────────────────────────────

def test_committed_default_allowlist_empty_and_strict():
    # Default parameter is None (no baked-in dates), and parsing yields empty set.
    sig = inspect.signature(fp.run_bounded_integrity_build)
    assert sig.parameters["fetch_absent_allowlist"].default is None
    assert fp.parse_fetch_absent_allowlist(None) == set()
    assert fp.parse_fetch_absent_allowlist([]) == set()
    # 2022-11-10 is NOT baked into committed defaults anywhere in the source.
    src = open(fp.__file__).read()
    code = "\n".join(ln for ln in src.splitlines() if not ln.lstrip().startswith("#"))
    assert "2022-11-10" not in code
    assert "20221110" not in code


# ── exception classifier unit checks ─────────────────────────────────────────

def test_classify_fetch_exception_kinds():
    assert fp.classify_fetch_exception(_http_404()) == "http_404"
    assert fp.classify_fetch_exception(_http_503()) == "retryable_transient"
    assert fp.classify_fetch_exception(
        urllib.error.HTTPError("u", 429, "Too Many", None, None)) == "retryable_transient"
    assert fp.classify_fetch_exception(http.client.IncompleteRead(b"")) == "retryable_transient"
    assert fp.classify_fetch_exception(TimeoutError()) == "retryable_transient"
    assert fp.classify_fetch_exception(ConnectionResetError()) == "retryable_transient"
    assert fp.classify_fetch_exception(urllib.error.URLError("boom")) == "retryable_transient"
    # other HTTP 4xx and unrelated errors are fatal (never retried).
    assert fp.classify_fetch_exception(
        urllib.error.HTTPError("u", 403, "Forbidden", None, None)) == "fatal"
    assert fp.classify_fetch_exception(ValueError("nope")) == "fatal"


# ── §2 transient fetch failure then success (bounded retry recovers) ─────────

class _FlakyTransient:
    """Raises a transient exception the first `k` times a flaky date is requested,
    then serves its payload. Non-flaky dates serve immediately."""

    def __init__(self, payloads, flaky, exc_factory):
        self.payloads = payloads
        self.remaining = dict(flaky)
        self.exc_factory = exc_factory
        self.dates = []

    def __call__(self, source_file_date, url):
        self.dates.append(source_file_date)
        if self.remaining.get(source_file_date, 0) > 0:
            self.remaining[source_file_date] -= 1
            raise self.exc_factory()
        return self.payloads[source_file_date]


def _ten_day_window(base):
    present = [base + datetime.timedelta(days=i) for i in range(10)]
    payloads = {f: _payload([_row(_iso(f))]) for f in present}
    file_map = {fp.expected_source_filename(d): payloads[d] for d in present}
    md5_b, size_b = _mk_manifests(file_map)
    return present, payloads, md5_b, size_b


def test_transient_then_success_byte_identical_and_bounded_buffer(monkeypatch, tmp_path):
    base = _d(2015, 1, 1)
    present, payloads, md5_b, size_b = _ten_day_window(base)
    # Baseline: all-success run.
    base_res = fp.run_bounded_integrity_build(
        _iso(present[0]), _iso(present[-1]), out_dir=str(tmp_path / "base"),
        md5sums_bytes=md5_b, filesizes_bytes=size_b,
        fetch_callable=_Fetcher(payloads), sleep_fn=_FakeSleep(),
        **_guarded(monkeypatch))
    # Flaky: day 5 raises IncompleteRead twice (< budget 4), then succeeds.
    sleep = _FakeSleep()
    flaky = _FlakyTransient(payloads, {present[4]: 2}, lambda: http.client.IncompleteRead(b""))
    res = fp.run_bounded_integrity_build(
        _iso(present[0]), _iso(present[-1]), out_dir=str(tmp_path / "flaky"),
        md5sums_bytes=md5_b, filesizes_bytes=size_b,
        fetch_callable=flaky, sleep_fn=sleep, **_guarded(monkeypatch))
    # Byte-identical archive despite transient retries.
    assert res["archive_artifact"]["sha256"] == base_res["archive_artifact"]["sha256"]
    # Retry happened before buffering -> high-water stays the fixed bound 2*EDD+1.
    assert res["max_buffered_source_file_blocks"] == 2 * archive.ELIGIBILITY_DELTA_DAYS + 1
    assert res["max_buffered_source_file_blocks"] == 3
    assert base_res["max_buffered_source_file_blocks"] == 3
    # Backoff was actually exercised (>=2 transient retries slept).
    assert len(sleep.calls) >= 2


def test_transient_then_success_for_http_5xx(monkeypatch, tmp_path):
    base = _d(2015, 3, 1)
    present, payloads, md5_b, size_b = _ten_day_window(base)
    base_res = fp.run_bounded_integrity_build(
        _iso(present[0]), _iso(present[-1]), out_dir=str(tmp_path / "b"),
        md5sums_bytes=md5_b, filesizes_bytes=size_b,
        fetch_callable=_Fetcher(payloads), sleep_fn=_FakeSleep(), **_guarded(monkeypatch))
    flaky = _FlakyTransient(payloads, {present[3]: 1}, _http_503)
    res = fp.run_bounded_integrity_build(
        _iso(present[0]), _iso(present[-1]), out_dir=str(tmp_path / "f"),
        md5sums_bytes=md5_b, filesizes_bytes=size_b,
        fetch_callable=flaky, sleep_fn=_FakeSleep(), **_guarded(monkeypatch))
    assert res["archive_artifact"]["sha256"] == base_res["archive_artifact"]["sha256"]


# ── §3 retry exhaustion -> clean hard-fail, no silent tolerance ──────────────

def test_retry_exhaustion_hard_fails(monkeypatch, tmp_path):
    f = _d(2016, 2, 10)
    payloads = {f: _payload([_row(_iso(f))])}
    md5_b, size_b = _mk_manifests({fp.expected_source_filename(f): payloads[f]})

    def _always_incomplete(dd, url):
        raise http.client.IncompleteRead(b"")

    out = tmp_path / "out"
    with pytest.raises(fp.TransientFetchError) as ei:
        fp.run_bounded_integrity_build(
            _iso(f), _iso(f), out_dir=str(out),
            md5sums_bytes=md5_b, filesizes_bytes=size_b,
            fetch_callable=_always_incomplete, sleep_fn=_FakeSleep(),
            max_transient_retries=2, **_guarded(monkeypatch))
    assert fp.expected_source_filename(f) in str(ei.value)
    assert not (out / "ttg_approved_fields_archive.csv").exists()
    assert not (out / "ttg_archive_provenance_manifest.json").exists()


# ── §4 / §6 stable 404 on an ALLOWLISTED date: tolerated + coverage propagation

def _nov_window():
    """2022-11-06..2022-11-14, all present-in-both, one row per file (sqldate=f)."""
    present = [_d(2022, 11, d) for d in range(6, 15)]
    payloads = {f: _payload([_row(_iso(f))]) for f in present}
    file_map = {fp.expected_source_filename(d): payloads[d] for d in present}
    md5_b, size_b = _mk_manifests(file_map)
    return present, payloads, md5_b, size_b


class _Stable404Fetcher:
    """Serves payloads except for `absent_dates`, which always raise HTTP 404."""

    def __init__(self, payloads, absent_dates):
        self.payloads = payloads
        self.absent = set(absent_dates)
        self.dates = []

    def __call__(self, source_file_date, url):
        self.dates.append(source_file_date)
        if source_file_date in self.absent:
            raise _http_404(url)
        return self.payloads[source_file_date]


def test_stable_404_allowlisted_continues_as_tolerated_gap(monkeypatch, tmp_path):
    present, payloads, md5_b, size_b = _nov_window()
    miss = _d(2022, 11, 10)
    fetcher = _Stable404Fetcher(payloads, {miss})
    out = tmp_path / "out"
    res = fp.run_bounded_integrity_build(
        "2022-11-06", "2022-11-14", out_dir=str(out),
        md5sums_bytes=md5_b, filesizes_bytes=size_b, fetch_callable=fetcher,
        fetch_absent_allowlist=["2022-11-10"], sleep_fn=_FakeSleep(),
        **_guarded(monkeypatch))
    # Build COMPLETED (archive + manifest written), not aborted.
    assert (out / "ttg_approved_fields_archive.csv").exists()
    assert (out / "ttg_archive_provenance_manifest.json").exists()
    # The missing date is recorded as an allowlisted fetch-absent gap.
    assert res["fetch_absent_allowlisted_source_dates"] == ["2022-11-10"]
    assert "20221110.export.CSV.zip" in res["fetch_absent_allowlisted_source_files"]
    assert res["fetch_absent_allowlist_supplied"] == ["2022-11-10"]
    # It is NOT counted as a mutual-absence manifest gap.
    assert res["tolerated_gap_dates"] == []


def test_stable_404_allowlisted_coverage_propagation_two_sided(monkeypatch, tmp_path):
    present, payloads, md5_b, size_b = _nov_window()
    miss = _d(2022, 11, 10)
    fetcher = _Stable404Fetcher(payloads, {miss})
    res = fp.run_bounded_integrity_build(
        "2022-11-06", "2022-11-14", out_dir=str(tmp_path / "out"),
        md5sums_bytes=md5_b, filesizes_bytes=size_b, fetch_callable=fetcher,
        fetch_absent_allowlist=["2022-11-10"], sleep_fn=_FakeSleep(),
        **_guarded(monkeypatch))
    # Excluded: the missing source date AND both neighbors (support fan-out).
    for iso in ("2022-11-09", "2022-11-10", "2022-11-11"):
        assert iso not in res["primary_covered_sqldates"]
        assert iso in res["ledger_gap_uncovered_sqldates"]
        assert "20221110.export.CSV.zip" in res["coverage_ledger"][iso]["gap_causes"]
        assert iso in res["fetch_absent_coverage_loss_sqldates"]
    # Retained: neighbors one step further out (inside nominal primary window).
    for iso in ("2022-11-08", "2022-11-12"):
        assert iso in res["primary_covered_sqldates"]
        assert res["coverage_ledger"][iso]["state"] == fp.COVERAGE_COVERED
    # The exclusion routes through the SAME oracle the streamed row-filter uses.
    avail = set(present) - {miss}
    for iso in ("2022-11-09", "2022-11-10", "2022-11-11"):
        assert archive.fetched_set_fully_covers(datetime.date.fromisoformat(iso), avail) is False
    for iso in ("2022-11-08", "2022-11-12"):
        assert archive.fetched_set_fully_covers(datetime.date.fromisoformat(iso), avail) is True
    # The missing file was probed (initial + stability re-check) but never served.
    assert miss in fetcher.dates


# ── §5 / §9 stable 404 on a NON-allowlisted date: terminal hard-fail ─────────

def test_stable_404_non_allowlisted_hard_fails(monkeypatch, tmp_path):
    present, payloads, md5_b, size_b = _nov_window()
    miss = _d(2022, 11, 10)
    fetcher = _Stable404Fetcher(payloads, {miss})
    out = tmp_path / "out"
    with pytest.raises(fp.ManifestPresentButUnavailableError) as ei:
        fp.run_bounded_integrity_build(
            "2022-11-06", "2022-11-14", out_dir=str(out),
            md5sums_bytes=md5_b, filesizes_bytes=size_b, fetch_callable=fetcher,
            fetch_absent_allowlist=[],  # empty/strict
            sleep_fn=_FakeSleep(), **_guarded(monkeypatch))
    assert "20221110.export.CSV.zip" in str(ei.value)
    assert not (out / "ttg_approved_fields_archive.csv").exists()
    assert not (out / "ttg_archive_provenance_manifest.json").exists()


def test_unknown_stable_404_hard_fails_with_default_allowlist(monkeypatch, tmp_path):
    # No allowlist argument at all -> default empty/strict -> unknown 404 stops
    # the build for human review (present-in-both, stable 404, not allowlisted).
    f = _d(2017, 8, 3)
    payloads = {f: _payload([_row(_iso(f))])}
    md5_b, size_b = _mk_manifests({fp.expected_source_filename(f): payloads[f]})

    def _stable404(dd, url):
        raise _http_404(url)

    out = tmp_path / "out"
    with pytest.raises(fp.ManifestPresentButUnavailableError):
        fp.run_bounded_integrity_build(
            _iso(f), _iso(f), out_dir=str(out),
            md5sums_bytes=md5_b, filesizes_bytes=size_b, fetch_callable=_stable404,
            sleep_fn=_FakeSleep(), **_guarded(monkeypatch))
    assert not (out / "ttg_approved_fields_archive.csv").exists()


def test_unstable_404_recovers_and_is_not_tolerated_silently(monkeypatch, tmp_path):
    # A first 404 whose stability re-check RECOVERS must yield the real bytes and
    # complete normally (not classified as manifest-listed-but-unavailable).
    f = _d(2018, 4, 10)
    payloads = {f: _payload([_row(_iso(f))])}
    md5_b, size_b = _mk_manifests({fp.expected_source_filename(f): payloads[f]})
    state = {"n": 0}

    def _flaky_404_then_ok(dd, url):
        state["n"] += 1
        if state["n"] == 1:
            raise _http_404(url)   # first probe 404
        return payloads[dd]        # re-check recovers

    res = fp.run_bounded_integrity_build(
        _iso(f), _iso(f), out_dir=str(tmp_path / "out"),
        md5sums_bytes=md5_b, filesizes_bytes=size_b,
        fetch_callable=_flaky_404_then_ok, sleep_fn=_FakeSleep(),
        **_guarded(monkeypatch))
    assert res["fetch_absent_allowlisted_source_dates"] == []


# ── §7 existing 2014 mutual-absence gap regression (unification preserved) ────

def _run_mutual_gap(monkeypatch, tmp_path, start_iso, end_iso, gap_days, out):
    start = datetime.date.fromisoformat(start_iso)
    end = datetime.date.fromisoformat(end_iso)
    alld = []
    d = start
    while d <= end:
        alld.append(d)
        d += datetime.timedelta(days=1)
    gaps = set(gap_days)
    present = [d for d in alld if d not in gaps]
    payloads = {f: _payload([_row(_iso(f))]) for f in present}
    # gap days absent from BOTH manifests -> mutual-absence tolerated gaps.
    file_map = {fp.expected_source_filename(d): payloads[d] for d in present}
    md5_b, size_b = _mk_manifests(file_map)
    res = fp.run_bounded_integrity_build(
        start_iso, end_iso, out_dir=str(tmp_path / out),
        md5sums_bytes=md5_b, filesizes_bytes=size_b,
        fetch_callable=_Fetcher(payloads), sleep_fn=_FakeSleep(),
        **_guarded(monkeypatch))
    return res


def test_2014_consecutive_mutual_absence_gap_regression(monkeypatch, tmp_path):
    gaps = [_d(2014, 1, 23), _d(2014, 1, 24), _d(2014, 1, 25)]
    res = _run_mutual_gap(monkeypatch, tmp_path, "2014-01-20", "2014-01-28", gaps, "a")
    excluded = ["2014-01-22", "2014-01-23", "2014-01-24", "2014-01-25", "2014-01-26"]
    for iso in excluded:
        assert iso in res["ledger_gap_uncovered_sqldates"]
        assert iso not in res["primary_covered_sqldates"]
    # Neighbors outside the fan-out remain covered.
    for iso in ("2014-01-21", "2014-01-27"):
        assert iso in res["primary_covered_sqldates"]
    # These are mutual-absence manifest gaps, NOT fetch-absent allowlisted.
    assert res["fetch_absent_allowlisted_source_dates"] == []
    assert set(res["tolerated_gap_dates"]) == {g.isoformat() for g in gaps}


def test_2014_single_mutual_absence_gap_regression(monkeypatch, tmp_path):
    res = _run_mutual_gap(monkeypatch, tmp_path, "2014-03-16", "2014-03-22",
                          [_d(2014, 3, 19)], "b")
    for iso in ("2014-03-18", "2014-03-19", "2014-03-20"):
        assert iso in res["ledger_gap_uncovered_sqldates"]
        assert iso not in res["primary_covered_sqldates"]
    for iso in ("2014-03-17", "2014-03-21"):
        assert iso in res["primary_covered_sqldates"]
    assert res["tolerated_gap_dates"] == ["2014-03-19"]


# ── integrity failures are never masked by retry ─────────────────────────────

def test_retry_does_not_mask_integrity_failure(monkeypatch, tmp_path):
    # A file that fetches successfully (no transport error) but whose bytes fail
    # the official MD5 stays a hard IntegrityVerificationError — retry never runs.
    f = _d(2019, 5, 5)
    payloads = {f: _payload([_row(_iso(f))])}
    md5_b, size_b = _mk_manifests({fp.expected_source_filename(f): payloads[f]})
    out = tmp_path / "out"
    with pytest.raises(fp.IntegrityVerificationError):
        fp.run_bounded_integrity_build(
            _iso(f), _iso(f), out_dir=str(out),
            md5sums_bytes=md5_b, filesizes_bytes=size_b,
            fetch_callable=lambda dd, u: b"CORRUPT-bytes", sleep_fn=_FakeSleep(),
            **_guarded(monkeypatch))
    assert not (out / "ttg_approved_fields_archive.csv").exists()


# ── local_archive.py remains byte-identical (amendment is fetch-module only) ──

def test_local_archive_unchanged():
    import os
    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        "src", "lane2_type_tone_goldstein_local_archive.py")
    with open(path, "rb") as fh:
        got = hashlib.sha256(fh.read()).hexdigest()
    assert got == "6a3d715e078c796391a930270c1f34a086e6ef9df2d663752d1922241ee5f40d"
